stages:
  - build
  - sync


build:node:16.20.0:
  stage: build
  image: node:16.20.0
  script:
    - npm i
    - npm run build
    - npm run electron:build
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - node_modules/
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  # 极狐GitLab中文文档：https://docs.gitlab.cn/jh/ci/yaml/index.html#rules
  rules:
    # PR 到 main 分支时预执行
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    # PR 合并到 main 后执行、推送到 main 分支时
    - if: $CI_COMMIT_BRANCH == "main"


build:node:18.16.0:
  stage: build
  image: node:18.16.0
  script:
    - npm i
    - npm run build
    - npm run electron:build
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - node_modules/
  # https://docs.gitlab.com/ee/ci/yaml/index.html#rules
  # 极狐GitLab中文文档：https://docs.gitlab.cn/jh/ci/yaml/index.html#rules
  rules:
    # PR 到 main 分支时预执行
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    # PR 合并到 main 后执行、推送到 main 分支时
    - if: $CI_COMMIT_BRANCH == "main"


include:
  - /sync.yml
