name: Build and Release Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [ 16.x, 18.x ]
        arch: [ x64 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          architecture: ${{ matrix.arch }}

      - name: Install dependencies
        run: npm i

      - name: Build Electron App
        run: npm run electron:build:linux:deb

      - run: ls release
      - run: ls release/*.*.*
