name: Push to JiHuLab
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.JIHULAB_ID_RSA }}
          name: "JiHuLab SSH Key"
          known_hosts: jihulab.com

      - name: Push code to JiHuLab
        run: |
          echo git@jihulab.com:$GITHUB_REPOSITORY.git
          git remote add jihulab git@jihulab.com:$GITHUB_REPOSITORY.git
          git pull --progress -v --no-rebase jihulab main
          git push -u jihulab main
